# Generated by Django 4.2.30 on 2026-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthorAvatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        default="https://picsum.photos/seed/photographer/200/200",
                        help_text="头像图片链接",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "作者头像",
                "verbose_name_plural": "作者头像",
            },
        ),
        migrations.CreateModel(
            name="AuthorInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="摄影师", help_text="作者姓名", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="热爱摄影，用镜头捕捉生活中的美好瞬间。",
                        help_text="作者简介",
                    ),
                ),
            ],
            options={
                "verbose_name": "作者信息",
                "verbose_name_plural": "作者信息",
            },
        ),
        migrations.CreateModel(
            name="CoverImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        default="https://picsum.photos/seed/photography-hero/1920/1080",
                        help_text="封面背景图片链接",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "封面图片",
                "verbose_name_plural": "封面图片",
            },
        ),
        migrations.CreateModel(
            name="CoverText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="影像集", help_text="封面主标题", max_length=200
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="每一帧都是时光的标本",
                        help_text="封面副标题",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "封面文字",
                "verbose_name_plural": "封面文字",
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        default="https://picsum.photos/seed/gallery/800/600",
                        help_text="作品图片链接",
                        max_length=500,
                    ),
                ),
                ("title", models.CharField(help_text="作品标题", max_length=200)),
                ("description", models.TextField(blank=True, help_text="作品描述")),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="排序编号（数字越小越靠前）"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否显示")),
            ],
            options={
                "verbose_name": "作品",
                "verbose_name_plural": "作品列表",
                "ordering": ["order"],
            },
        ),
    ]
