# Generated by Django 4.2.30 on 2026-06-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authoravatar",
            name="file",
            field=models.ImageField(
                blank=True,
                help_text="上传本地图片（优先于外部链接）",
                null=True,
                upload_to="avatars/",
            ),
        ),
        migrations.AddField(
            model_name="coverimage",
            name="file",
            field=models.ImageField(
                blank=True,
                help_text="上传本地图片（优先于外部链接）",
                null=True,
                upload_to="covers/",
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="file",
            field=models.ImageField(
                blank=True,
                help_text="上传本地图片（优先于外部链接）",
                null=True,
                upload_to="gallery/",
            ),
        ),
    ]
