# Generated by Django 4.2.30 on 2026-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0002_authoravatar_file_coverimage_file_galleryitem_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coverimage",
            options={"verbose_name": "封面设置", "verbose_name_plural": "封面设置"},
        ),
        migrations.AddField(
            model_name="coverimage",
            name="subtitle",
            field=models.CharField(
                blank=True,
                default="每一帧都是时光的标本",
                help_text="封面副标题",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="coverimage",
            name="title",
            field=models.CharField(
                default="影像集", help_text="封面主标题", max_length=200
            ),
        ),
    ]
