# Generated by Django 4.2.30 on 2026-06-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0003_add_title_subtitle_to_coverimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CoverText",
        ),
    ]
